
import br.com.edsonmoretti.acbr.monitorplus.comunicador.ACBrUtils;
import br.com.edsonmoretti.acbr.monitorplus.comunicador.exceptions.ACBrException;
import static br.com.edsonmoretti.acbr.monitorplus.comunicador.utils.TextUtils.extrarSecaoesDeIni;
import static br.com.edsonmoretti.acbr.monitorplus.comunicador.utils.TextUtils.lerTagIni;
import java.util.TreeMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Edson
 */
public class TesteTextUtils {
    //USE APENAS PARA TESTES

    public static void main(String[] args) {
        //String ini = "[DESCRICAO]ORIENTACAO=0FONTE=2MULTIPLICADOR_H=2MULTIPLICADOR_V=2VERTICAL=19HORIZONTAL=5[GTIN]ORIENTACAO=0FONTE=1MULTIPLICADOR_H=2MULTIPLICADOR_V=30VERTICAL=13HORIZONTAL=5[R$01]ORIENTACAO=0FONTE=3MULTIPLICADOR_H=3MULTIPLICADOR_V=2VERTICAL=0HORIZONTAL=7[PRECO01]ORIENTACAO=0FONTE=3MULTIPLICADOR_H=4MULTIPLICADOR_V=3VERTICAL=0HORIZONTAL=20[R$02]ORIENTACAO=0FONTE=2MULTIPLICADOR_H=2MULTIPLICADOR_V=2VERTICAL=3HORIZONTAL=5[PRECO02]ORIENTACAO=0FONTE=3MULTIPLICADOR_H=4MULTIPLICADOR_V=3VERTICAL=0HORIZONTAL=40[AMBOSPRECOS][ATACADO]ORIENTACAO=0FONTE=2MULTIPLICADOR_H=2MULTIPLICADOR_V=2VERTICAL=10HORIZONTAL=70[PRECO02]ORIENTACAO=0FONTE=2MULTIPLICADOR_H=2MULTIPLICADOR_V=2VERTICAL=5HORIZONTAL=70";
        String ini = "[CEDENTE]\n"
                + "Nome=GERALDO JOAO DA SILVA ME\n"
                + "CNPJCPF=10.493.367/0001-48\n"
                + "CodigoCedente=1\n"
                + "MODALIDADE=\n"
                + "CODTRANSMISSAO=\n"
                + "CONVENIO=\n"
                + "\n"
                + "[BANCO]\n"
                + "Numero=4\n"
                + "IndiceACBr=13\n"
                + "\n"
                + "[CONTA]\n"
                + "Conta=0000247\n"
                + "DigitoConta=6\n"
                + "Agencia=0315\n"
                + "DigitoAgencia=0\n"
                + "\n"
                + "[Titulo1]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=10/12/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17397     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000008\n"
                + "Carteira=4\n"
                + "ValorDocumento=150\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17397                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo2]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=10/11/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17396     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000007\n"
                + "Carteira=4\n"
                + "ValorDocumento=150\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17396                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo3]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=09/12/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17391     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000003\n"
                + "Carteira=4\n"
                + "ValorDocumento=775\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17391                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo4]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=09/11/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17390     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000002\n"
                + "Carteira=4\n"
                + "ValorDocumento=775\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17390                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo5]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=10/12/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17400     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000011\n"
                + "Carteira=4\n"
                + "ValorDocumento=150\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17400                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo6]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=10/11/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17399     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000010\n"
                + "Carteira=4\n"
                + "ValorDocumento=150\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17399                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo7]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=07/11/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17395     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000006\n"
                + "Carteira=4\n"
                + "ValorDocumento=290\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17395                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo8]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=08/01/2017\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17392     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000004\n"
                + "Carteira=4\n"
                + "ValorDocumento=775\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17392                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo9]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=10/10/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17389     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000001\n"
                + "Carteira=4\n"
                + "ValorDocumento=775\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=30/12/1899\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=0\n"
                + "SeuNumero=17389                    \n"
                + "CodTipoOcorrencia=toRetornoRegistroConfirmado\n"
                + "DescricaoTipoOcorrencia=02-Entrada Confirmada\n"
                + "\n"
                + "[Titulo10]\n"
                + "Sacado.Nome=\n"
                + "Sacado.CNPJCPF=\n"
                + "Vencimento=07/10/2016\n"
                + "DataDocumento=30/12/1899\n"
                + "NumeroDocumento=17398     \n"
                + "DataProcessamento=13/10/2016\n"
                + "NossoNumero=0000009\n"
                + "Carteira=4\n"
                + "ValorDocumento=200\n"
                + "DataOcorrencia=07/10/2016\n"
                + "DataCredito=10/10/2016\n"
                + "DataBaixa=30/12/1899\n"
                + "ValorDespesaCobranca=3,2\n"
                + "ValorAbatimento=0\n"
                + "ValorDesconto=0\n"
                + "ValorMoraJuros=0\n"
                + "ValorIOF=0\n"
                + "ValorOutrasDespesas=0\n"
                + "ValorOutrosCreditos=0\n"
                + "ValorRecebido=200\n"
                + "SeuNumero=17398                    \n"
                + "CodTipoOcorrencia=toRetornoLiquidado\n"
                + "DescricaoTipoOcorrencia=06-Liquidação normal";
//        System.out.println(lerTagIni("VeRsAo", ini));
//        System.out.println(lerTagIni("tpamb", ini));
//        System.out.println(lerTagIni("VERAPLIC", ini));
//        System.out.println(lerTagIni("DHRECBto", ini));
////        System.out.println(lerTagIni("xmOTIVO", ini));
//        System.out.println(lerTagIni("xmOTIVO", ini, "edson"));
//        System.out.println(lerTagIni("xmOTIVO", ini, "moretti"));
//        System.out.println(lerTagIni("xmOTIVO", ini, "status"));
//        System.out.println(lerTagIni("xmOTIVO", ini));
        System.out.println(lerTagIni("Nome", ini, "[CEDENTE]"));
        for (int i = 1; i < 9999; i++) {
            try {
                System.out.println("Data" + i);
                System.out.println(ACBrUtils.strDataToDateBR(lerTagIni("Vencimento", ini, "[Titulo" + i + "]")));
            } catch (ACBrException | NullPointerException ex) {
                break;
            }
        }

        TreeMap<String, String> extrarSecaoesDeIni = extrarSecaoesDeIni(ini);
        for (String secao : extrarSecaoesDeIni.keySet()) {
            System.out.println(secao);
            System.out.println(extrarSecaoesDeIni.get(secao));
        }
    }
}
